### ISSUE TITLE
Some info about costs

### ISSUE THREAD

**Issue by icicimov** [efschu/AP-HA-CIAB-ISER#1]
Hi,
First let me say good job done! Could you please add some info about the parts/total cost of the hardware? Also some photos of your rack/setup to complement your article :-). Thanks!

**Comment by efschu** [comment]
~ 8k €    for server w/o network gear
~ 9k €   for drives
~ 800 €  for 4x CX3 Pro + 2x switches (used on ebay)
~ 300 €  for 8x QSFP+ DAC cables

Nothing special about the look, it's a "standard" 2HE
https://www.supermicro.com/products/system/2U/2029/SSG-2029P-DN2R24L.cfm

I will update with some more performance stats when it comes to production

**Comment by icicimov** [comment]
Thanks would be great to see the update when in prod.
